/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gourmet.ui;

import gourmet.Table;

/**
 *
 * @author dodoc
 */
public class EncaisserAddition extends javax.swing.JDialog {

    /**
     * Creates new form EncaisserAddition
     */
    public EncaisserAddition(Table t,double prix) { 
        initComponents();
        Double prix_payer = prix;
        Integer couv = t.getCouverts();
        Consulter.setText("Consulter");
        Imprimer.setText("Imprimer");
        Encaisser.setText("Encaisser");
        OK.setText("OK");
        Annuler.setText("Annuler");
        
        p.setText(prix_payer.toString());
        table.setText(t.getNumero());
        couvert.setText(couv.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonECI = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Consulter = new javax.swing.JRadioButton();
        Imprimer = new javax.swing.JRadioButton();
        Encaisser = new javax.swing.JRadioButton();
        OK = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        table = new javax.swing.JTextField();
        couvert = new javax.swing.JTextField();
        p = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Table :");

        jLabel2.setText("Nombre de couverts :");

        jLabel3.setText("A PAYER :");

        buttonECI.add(Consulter);
        Consulter.setSelected(true);
        Consulter.setText("Consulter");
        Consulter.setToolTipText("Juste pour voir");

        buttonECI.add(Imprimer);
        Imprimer.setText("Imprimer");
        Imprimer.setToolTipText("Fabriquer souche");

        buttonECI.add(Encaisser);
        Encaisser.setText("Encaisser");
        Encaisser.setToolTipText("Enregistrer le payement");

        OK.setText("Ok");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });

        table.setEnabled(false);

        couvert.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        couvert.setEnabled(false);

        p.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(table)
                            .addComponent(couvert)
                            .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Consulter)
                        .addGap(18, 18, 18)
                        .addComponent(Imprimer)
                        .addGap(18, 18, 18)
                        .addComponent(Encaisser))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(OK)
                        .addGap(43, 43, 43)
                        .addComponent(Annuler)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(couvert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consulter)
                    .addComponent(Imprimer)
                    .addComponent(Encaisser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK)
                    .addComponent(Annuler))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        if(Consulter.isSelected()){
            System.out.println("Consulter appuye");
        } else if(Imprimer.isSelected()){
            System.out.println("Imprimer appuye");
        } else if(Encaisser.isSelected()){
            System.out.println("Encaisser appuye");
        }
        setVisible(false);
    }//GEN-LAST:event_OKActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        setVisible(false);
    }//GEN-LAST:event_AnnulerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JRadioButton Consulter;
    private javax.swing.JRadioButton Encaisser;
    private javax.swing.JRadioButton Imprimer;
    private javax.swing.JButton OK;
    private javax.swing.ButtonGroup buttonECI;
    private javax.swing.JTextField couvert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField p;
    private javax.swing.JTextField table;
    // End of variables declaration//GEN-END:variables
}
